---
specs:
  - name: tracey
    prefix: r
    source_url: "https://github.com/bearcove/tracey"
    include:
      - ../tracey/docs/spec/**/*.md
    impls:
      - name: main
        include:
          - crates/**/*.rs
        exclude:
          - target/**
        test_include: []
